# Generated by Django 4.2.19 on 2025-02-08 00:05

import actions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_useraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.CharField(default='volunteering', max_length=50),
        ),
        migrations.AddField(
            model_name='action',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='organization',
            field=models.CharField(default='default_org', max_length=100),
        ),
        migrations.AddField(
            model_name='useraction',
            name='is_trending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraction',
            name='trend_expires_at',
            field=models.DateTimeField(default=actions.models.default_trend_expiry),
        ),
        migrations.AlterField(
            model_name='action',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.CreateModel(
            name='TrendingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('category', 'Category'), ('organization', 'Organization')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('trend_type', 'name')},
            },
        ),
    ]
