# Generated by Django 4.2.19 on 2025-02-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_action_action_type_action_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
