# Generated by Django 5.1.5 on 2025-02-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_action_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thubnails/'),
        ),
    ]
