# Generated by Django 4.2.19 on 2025-03-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_action_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
