# Generated by Django 4.2.19 on 2025-03-10 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_customuser_date_of_birth_customuser_state_and_more'),
        ('custom_auth', 'fix_empty_usernames'),
    ]

    operations = [
    ]
